export declare const lightTheme: string;
export declare const darkTheme: string;
export declare const vars: {
    color: import("@vanilla-extract/private").MapLeafNodes<{
        "action-primary-base": string;
        "action-primary-hover": string;
        "action-primary-active": string;
        "action-secondary-base": string;
        "action-secondary-hover": string;
        "action-secondary-active": string;
        "action-muted-base": string;
        "action-muted-hover": string;
        "action-muted-active": string;
        contrast: string;
        white: string;
        black: string;
        "secondary-50": string;
        "secondary-100": string;
        "secondary-200": string;
        "secondary-300": string;
        "secondary-400": string;
        "secondary-500": string;
        "secondary-600": string;
        "secondary-700": string;
        "secondary-800": string;
        "secondary-900": string;
        "primary-50": string;
        "primary-100": string;
        "primary-200": string;
        "primary-300": string;
        "primary-400": string;
        "primary-500": string;
        "primary-600": string;
        "primary-700": string;
        "primary-800": string;
        "primary-900": string;
        "muted-50": string;
        "muted-100": string;
        "muted-200": string;
        "muted-300": string;
        "muted-400": string;
        "muted-500": string;
        "muted-600": string;
        "muted-700": string;
        "muted-800": string;
        "muted-900": string;
        "surface-0": string;
        "surface-1": string;
        "surface-2": string;
        "text-base": string;
        "text-label": string;
        "text-heading": string;
    }, import("@vanilla-extract/private").CSSVarFunction>;
    space: import("@vanilla-extract/private").MapLeafNodes<{
        none: string;
        xxxs: string;
        xxs: string;
        xs: string;
        sm: string;
        md: string;
        lg: string;
        xl: string;
        xxl: string;
    }, import("@vanilla-extract/private").CSSVarFunction>;
    size: import("@vanilla-extract/private").MapLeafNodes<{
        "100%": string;
        container: string;
    }, import("@vanilla-extract/private").CSSVarFunction>;
    radius: import("@vanilla-extract/private").MapLeafNodes<{
        xs: string;
        sm: string;
        md: string;
        round: string;
        none: string;
    }, import("@vanilla-extract/private").CSSVarFunction>;
    font: import("@vanilla-extract/private").MapLeafNodes<{
        family: {
            body: string;
            heading: string;
        };
        size: {
            root: string;
            base: string;
            small: string;
            medium: string;
            label: string;
            h1: string;
            h2: string;
            h3: string;
            h4: string;
            h5: string;
        };
    }, import("@vanilla-extract/private").CSSVarFunction>;
};
//# sourceMappingURL=theme.css.d.ts.map